header:
  version: 11
  includes:
    - meta-avocado-example/conf/kas/peridio.yml

build_system: oe

repos:
  bitbake:
    url: https://git.openembedded.org/bitbake
    commit: 0a33b560233b983456178541603ab96fea22238b
    branch: '2.8'
    layers:
      .: excluded

  meta-avocado:
    path: meta-avocado/meta-avocado

  meta-avocado-example:
    path: meta-avocado/meta-avocado-example

  meta-openembedded:
    url: https://git.openembedded.org/meta-openembedded
    commit: a72010b414ee3d73888ac9cb4e310e8f05e13aea
    branch: scarthgap
    layers:
      meta-oe:
      meta-perl:
      meta-python:
      meta-networking:
      meta-filesystems:
      meta-multimedia:

  openembedded-core:
    url: https://git.openembedded.org/openembedded-core
    commit: 294a7dbe44f6b7c8d3a1de8c2cc182af37c4f916
    branch: scarthgap
    layers:
      meta:

  meta-virtualization:
    url: https://git.yoctoproject.org/meta-virtualization
    commit: 1a547c0aa0d75c4143cbb66de6e653d51cdc8bda
    branch: scarthgap
    layers:
      .:

distro: avocado

env:
    TEMPLATECONF: ../meta-avocado/conf/templates/default

local_conf_header:
  meta-avocado: |
    USER_CLASSES:append = " buildhistory buildstats buildstats-summary"
    EXTRA_IMAGE_FEATURES ?= "debug-tweaks"
    PACKAGECONFIG:append:pn-gnutls = " p11-kit"

  sdk: |
    CONF_VERSION = "2"

target:
 - avocado-image-base
